define([
    'dgrid/Selector',
    'dgrid/util/misc',
    'dgrid/util/has-css3',
    'dgrid/util/touch',
    'dgrid/Tree',
    'dgrid/Grid',
    'dgrid/ColumnSet',
    'dgrid/List',
    'dgrid/extensions/DnD',
    'dgrid/extensions/ColumnHider',
    'dgrid/extensions/SingleQuery',
    'dgrid/extensions/CompoundColumns',
    // 'dgrid/extensions/nls/sl/columnHider',
    // 'dgrid/extensions/nls/sl/pagination',
    // 'dgrid/extensions/nls/sk/pagination',
    // 'dgrid/extensions/nls/columnHider',
    // 'dgrid/extensions/nls/ja/pagination',
    // 'dgrid/extensions/nls/ru/columnHider',
    // 'dgrid/extensions/nls/ru/pagination',
    // 'dgrid/extensions/nls/ro/columnHider',
    // 'dgrid/extensions/nls/ro/pagination',
    // 'dgrid/extensions/nls/zh-cn/pagination',
    // 'dgrid/extensions/nls/pt/pagination',
    // 'dgrid/extensions/nls/pagination',
    // 'dgrid/extensions/nls/ar/pagination',
    // 'dgrid/extensions/nls/de/pagination',
    // 'dgrid/extensions/nls/fr/pagination',
    // 'dgrid/extensions/nls/es/columnHider',
    // 'dgrid/extensions/nls/es/pagination',
    // 'dgrid/extensions/nls/zh-hk/pagination',
    // 'dgrid/extensions/nls/th/pagination',
    'dgrid/extensions/ColumnReorder',
    'dgrid/extensions/ColumnResizer',
    // 'dgrid/extensions/Pagination',
    'dgrid/Editor',
    'dgrid/Selection',
    'dgrid/Keyboard',
    'dgrid/_StoreMixin',
    'dgrid/CellSelection',
    'dgrid/OnDemandList',
    'dgrid/OnDemandGrid'
], function(
    Selector,
    util_misc,
    util_has-css3,
    util_touch,
    Tree,
    Grid,
    ColumnSet,
    List,
    extensions_DnD,
    // extensions_ColumnHider,
    extensions_SingleQuery,
    extensions_CompoundColumns,
    // extensions_nls_sl_columnHider,
    // extensions_nls_sl_pagination,
    // extensions_nls_sk_pagination,
    // extensions_nls_columnHider,
    // extensions_nls_ja_pagination,
    // extensions_nls_ru_columnHider,
    // extensions_nls_ru_pagination,
    // extensions_nls_ro_columnHider,
    // extensions_nls_ro_pagination,
    // extensions_nls_zh-cn_pagination,
    // extensions_nls_pt_pagination,
    // extensions_nls_pagination,
    // extensions_nls_ar_pagination,
    // extensions_nls_de_pagination,
    // extensions_nls_fr_pagination,
    // extensions_nls_es_columnHider,
    // extensions_nls_es_pagination,
    // extensions_nls_zh-hk_pagination,
    // extensions_nls_th_pagination,
    extensions_ColumnReorder,
    extensions_ColumnResizer,
    // extensions_Pagination,
    Editor,
    Selection,
    Keyboard,
    _StoreMixin,
    CellSelection,
    OnDemandList,
    OnDemandGrid
) {
    return {
        Selector: Selector,
        util: {
            misc: util_misc,
            'has-css3': util_has-css3,
            touch: util_touch,
        },
        Tree: Tree,
        Grid: Grid,
        ColumnSet: ColumnSet,
        List: List,
        extensions: {
            DnD: extensions_DnD,
            // ColumnHider: extensions_ColumnHider,
            SingleQuery: extensions_SingleQuery,
            CompoundColumns: extensions_CompoundColumns,
            // nls: {
            //     sl: {
            //         columnHider: extensions_nls_sl_columnHider,
            //         pagination: extensions_nls_sl_pagination,
            //     },
            //     sk: {
            //         pagination: extensions_nls_sk_pagination,
            //     },
            //     ja: {
            //         pagination: extensions_nls_ja_pagination,
            //     },
            //     ru: {
            //         columnHider: extensions_nls_ru_columnHider,
            //         pagination: extensions_nls_ru_pagination,
            //     },
            //     ro: {
            //         columnHider: extensions_nls_ro_columnHider,
            //         pagination: extensions_nls_ro_pagination,
            //     },
            //     'zh-cn': {
            //         pagination: extensions_nls_zh-cn_pagination,
            //     },
            //     pt: {
            //         pagination: extensions_nls_pt_pagination,
            //     },
            //     ar: {
            //         pagination: extensions_nls_ar_pagination,
            //     },
            //     de: {
            //         pagination: extensions_nls_de_pagination,
            //     },
            //     fr: {
            //         pagination: extensions_nls_fr_pagination,
            //     },
            //     es: {
            //         columnHider: extensions_nls_es_columnHider,
            //         pagination: extensions_nls_es_pagination,
            //     },
            //     'zh-hk': {
            //         pagination: extensions_nls_zh-hk_pagination,
            //     },
            //     th: {
            //         pagination: extensions_nls_th_pagination,
            //     },
            //     columnHider: extensions_nls_columnHider,
            //     pagination: extensions_nls_pagination
            // },
            // ColumnReorder: extensions_ColumnReorder,
            // ColumnResizer: extensions_ColumnResizer,
            // Pagination: extensions_Pagination,
        }
        Editor: Editor,
        Selection: Selection,
        Keyboard: Keyboard,
        _StoreMixin: _StoreMixin,
        CellSelection: CellSelection,
        OnDemandList: OnDemandList,
        OnDemandGrid: OnDemandGrid,
    };
};
